name: psy_search
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_stack_widget: any
  auto_size_text: any
  cached_network_image: any
  cloud_firestore: any
  cloud_firestore_platform_interface: any
  cloud_firestore_web: any
  collection: any
  dropdown_button2: any
  easy_debounce: any
  file_picker: any
  firebase_auth: any
  firebase_auth_platform_interface: any
  firebase_auth_web: any
  firebase_core: any
  firebase_core_platform_interface: any
  firebase_core_web: any
  firebase_performance: any
  firebase_performance_platform_interface: any
  firebase_performance_web: any
  firebase_storage: any
  firebase_storage_platform_interface: any
  firebase_storage_web: any
  flutter_animate: any
  flutter_cache_manager: any
  flutter_plugin_android_lifecycle: any
  font_awesome_flutter: any
  from_css_color: any
  go_router: any
  google_fonts: any
  google_maps_flutter: any
  google_sign_in: any
  google_sign_in_android: any
  google_sign_in_ios: any
  google_sign_in_platform_interface: any
  google_sign_in_web: any
  image_picker: any
  image_picker_android: any
  image_picker_for_web: any
  image_picker_ios: any
  image_picker_platform_interface: any
  intl: any
  json_path: any
  mime_type: any
  page_transition: any
  path_provider: any
  path_provider_android: any
  path_provider_foundation: any
  path_provider_platform_interface: any
  photo_view: any
  plugin_platform_interface: any
  provider: any
  rxdart: any
  shared_preferences: any
  shared_preferences_android: any
  shared_preferences_foundation: any
  shared_preferences_platform_interface: any
  shared_preferences_web: any
  sign_in_with_apple: any
  sign_in_with_apple_platform_interface: any
  sign_in_with_apple_web: any
  sqflite: any
  stream_transform: any
  timeago: any
  url_launcher: any
  url_launcher_android: any
  url_launcher_ios: any
  url_launcher_platform_interface: any
  video_player: any
  video_player_android: any
  video_player_avfoundation: any
  video_player_platform_interface: any
  video_player_web: any
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cloud_firestore: 4.15.7
  cloud_firestore_platform_interface: 6.1.8
  cloud_firestore_web: 3.10.7
  collection: 1.18.0
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  firebase_analytics: 10.8.8
  firebase_analytics_platform_interface: 3.9.8
  firebase_analytics_web: 0.5.5+20
  firebase_auth: 4.17.7
  firebase_auth_platform_interface: 7.1.7
  firebase_auth_web: 5.9.7
  firebase_core: 2.26.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.11.5
  firebase_performance: 0.9.3+16
  firebase_performance_platform_interface: 0.1.4+24
  firebase_performance_web: 0.1.4+24
  fluster:
  flutter_animate: 4.1.1+1
  flutter_blurhash: 0.8.2
  flutter_cache_manager: 3.3.1
  flutter_map:
  flutter_map_marker_cluster:
  flutter_map_supercluster:
  flutter_native_splash: 2.3.1
  flutter_rating_bar: 4.0.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  geolocator: 10.1.0
  geolocator_android: 4.4.0
  geolocator_apple: 2.3.2
  geolocator_platform_interface: 4.2.0
  geolocator_web: 2.2.0
  go_router: 7.1.1
  google_fonts: 6.1.0
  google_maps_flutter:
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  image:
  intl: 0.18.1
  json_path: 0.6.2
  latlong2:
  octo_image: 2.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  percent_indicator: 4.2.2
  plugin_platform_interface: 2.1.8
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: 2.2.6
  stream_transform: 2.1.0
  text_search: 1.0.1
  timeago: 3.2.2
  universal_io: 2.2.2
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  xml: 6.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.0
  intl: ^0.18.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: any
  flutter_lints: any
  lints: any

  flutter_test:
    sdk: flutter
  test: ^1.25.2


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.jpg'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

