name: psy_search
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_stack_widget: ^0.0.4
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cloud_firestore: ^4.15.5
  cloud_firestore_platform_interface: ^6.1.6
  cloud_firestore_web: ^3.10.5
  collection: ^1.18.0
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.3
  file_picker: 6.1.1
  firebase_auth: 4.17.4
  firebase_auth_platform_interface: ^7.1.5
  firebase_auth_web: 5.9.4
  firebase_core: 2.25.4
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.11.4
  firebase_performance: ^0.9.3+14
  firebase_performance_platform_interface: ^0.1.4+22
  firebase_performance_web: ^0.1.4+22
  firebase_storage: ^11.6.5
  firebase_storage_platform_interface: ^5.1.8
  firebase_storage_web: ^3.6.22
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.4
  flutter_map_marker_popup: ^6.1.2
  flutter_plugin_android_lifecycle: 2.0.17
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  geolocator: ^11.0.0
  geolocator_android: ^4.5.2
  geolocator_apple: ^2.3.5
  geolocator_platform_interface: ^4.2.1
  geolocator_web: ^3.0.0
  go_router: 13.2.0
  google_fonts: 6.1.0
  google_maps: ^6.3.0
  google_maps_flutter: ^2.5.3
  google_maps_flutter_platform_interface: ^2.4.3
  google_maps_flutter_web: ^0.5.4+3
  google_sign_in: 6.2.1
  google_sign_in_android: 6.1.21
  google_sign_in_ios: ^5.7.4
  google_sign_in_platform_interface: 2.4.5
  google_sign_in_web: 0.12.3+2
  image_picker: ^1.0.7
  image_picker_android: ^0.8.9+3
  image_picker_for_web: ^3.0.2
  image_picker_ios: ^0.8.9+1
  image_picker_platform_interface: ^2.9.3
  intl: ^0.18.1
  json_path: ^0.7.0
  latlong2: ^0.9.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  photo_view: 0.14.0
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.1
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.2.2
  sign_in_with_apple: ^5.0.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  sqflite: ^2.3.2
  stream_transform: 2.1.0
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  url_launcher_android: ^6.2.2
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.1
  video_player: ^2.8.2
  video_player_android: ^2.4.11
  video_player_avfoundation: ^2.5.6
  video_player_platform_interface: ^6.2.2
  video_player_web: ^2.1.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  fluster: ^1.2.0
  image: ^4.1.7
  async: ^2.11.0
  http: ^1.2.0
  typed_data: ^1.3.2
  flutter_map_marker_cluster: ^1.3.4
  latlng: ^2.0.5

dependency_overrides:
  intl: ^0.18.1
  collection: ^1.18.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^3.0.1
  lints: 3.0.0

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.jpg'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

