name: Flutter Firebase Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # updated to use v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.1.4' # Ensure this version satisfies the Dart SDK version >=3.1.0 requirement
        channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-web
    - run: flutter build web
    - name: Archive Production Artifact
      uses: actions/upload-artifact@v2  # updated to use v2
      with:
        name: web-build
        path: build/web
  deploy:
    needs: build_web
    runs-on: ubuntu-latest  
    steps:
      - name: checkout
        uses: actions/checkout@v2  # updated to use v2
      - name: Download Artifact
        uses: actions/download-artifact@v2  # updated to use v2
        with:
          name: web-build
          path: build/web
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_psysearch }}'
          channelId: live
          projectId: psysearch
